### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by throughnothing** [trezor/trezor-chrome-extension#1]
On OSX I had to run the snippet below instead of `npm run prepare` as the default `npm run prepare` did not work.  I had to add the `bak` arg as the extension for the interactive edit backup file, and also change all the `\\` to `\`.

I also think it would be good to default the documentation to use `./node_modules/protobufjs/bin/proto2js` instead of assuming `proto2js` is available globally (or add installing that globally to the setup docs).

```
sed -i bak 's/\(google\/protobuf\)/\.\/\1/' trezor-common/protob/config.proto && ./node_modules/protobufjs/bin/proto2js trezor-common/protob/config.proto -commonjs > config_proto_compiled.js
```

**Comment by karelbilek** [comment]
Thanks for pointing the first thing out. I will try it on OS X. The double backslashes are correct though, because it¨s in JSON's double quotes, so all backslashes have to be double-escaped.

The second thing - it's not necessary, because "npm install" installs it correctly (with protobuf.js), and it uses the default "node_modules/.bin" as part of PATH. I will look at the sed thing though!

**Comment by karelbilek** [comment]
Oh and another note, the extension is now useless, it works only in
internal development version of mytrezor/trezor.js. We will be adding the
support soon.

**Comment by karelbilek** [comment]
corrected
